// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: qubic.proto

package protobuff

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Balance
type Balance struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance                    int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ValidForTick               uint32                 `protobuf:"varint,3,opt,name=valid_for_tick,json=validForTick,proto3" json:"valid_for_tick,omitempty"`
	LatestIncomingTransferTick uint32                 `protobuf:"varint,4,opt,name=latest_incoming_transfer_tick,json=latestIncomingTransferTick,proto3" json:"latest_incoming_transfer_tick,omitempty"`
	LatestOutgoingTransferTick uint32                 `protobuf:"varint,5,opt,name=latest_outgoing_transfer_tick,json=latestOutgoingTransferTick,proto3" json:"latest_outgoing_transfer_tick,omitempty"`
	IncomingAmount             int64                  `protobuf:"varint,6,opt,name=incoming_amount,json=incomingAmount,proto3" json:"incoming_amount,omitempty"`
	OutgoingAmount             int64                  `protobuf:"varint,7,opt,name=outgoing_amount,json=outgoingAmount,proto3" json:"outgoing_amount,omitempty"`
	NumberOfIncomingTransfers  uint32                 `protobuf:"varint,8,opt,name=number_of_incoming_transfers,json=numberOfIncomingTransfers,proto3" json:"number_of_incoming_transfers,omitempty"`
	NumberOfOutgoingTransfers  uint32                 `protobuf:"varint,9,opt,name=number_of_outgoing_transfers,json=numberOfOutgoingTransfers,proto3" json:"number_of_outgoing_transfers,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_qubic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Balance) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Balance) GetValidForTick() uint32 {
	if x != nil {
		return x.ValidForTick
	}
	return 0
}

func (x *Balance) GetLatestIncomingTransferTick() uint32 {
	if x != nil {
		return x.LatestIncomingTransferTick
	}
	return 0
}

func (x *Balance) GetLatestOutgoingTransferTick() uint32 {
	if x != nil {
		return x.LatestOutgoingTransferTick
	}
	return 0
}

func (x *Balance) GetIncomingAmount() int64 {
	if x != nil {
		return x.IncomingAmount
	}
	return 0
}

func (x *Balance) GetOutgoingAmount() int64 {
	if x != nil {
		return x.OutgoingAmount
	}
	return 0
}

func (x *Balance) GetNumberOfIncomingTransfers() uint32 {
	if x != nil {
		return x.NumberOfIncomingTransfers
	}
	return 0
}

func (x *Balance) GetNumberOfOutgoingTransfers() uint32 {
	if x != nil {
		return x.NumberOfOutgoingTransfers
	}
	return 0
}

// GetBalanceRequest
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_qubic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetBalanceResponse
type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_qubic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

// BroadcastTransactionRequest
type BroadcastTransactionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EncodedTransaction string                 `protobuf:"bytes,1,opt,name=encoded_transaction,json=encodedTransaction,proto3" json:"encoded_transaction,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BroadcastTransactionRequest) Reset() {
	*x = BroadcastTransactionRequest{}
	mi := &file_qubic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastTransactionRequest) ProtoMessage() {}

func (x *BroadcastTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastTransactionRequest.ProtoReflect.Descriptor instead.
func (*BroadcastTransactionRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastTransactionRequest) GetEncodedTransaction() string {
	if x != nil {
		return x.EncodedTransaction
	}
	return ""
}

// BroadcastTransactionResponse
type BroadcastTransactionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeersBroadcasted   int32                  `protobuf:"varint,1,opt,name=peers_broadcasted,json=peersBroadcasted,proto3" json:"peers_broadcasted,omitempty"`
	EncodedTransaction string                 `protobuf:"bytes,2,opt,name=encoded_transaction,json=encodedTransaction,proto3" json:"encoded_transaction,omitempty"`
	TransactionId      string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BroadcastTransactionResponse) Reset() {
	*x = BroadcastTransactionResponse{}
	mi := &file_qubic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastTransactionResponse) ProtoMessage() {}

func (x *BroadcastTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastTransactionResponse.ProtoReflect.Descriptor instead.
func (*BroadcastTransactionResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastTransactionResponse) GetPeersBroadcasted() int32 {
	if x != nil {
		return x.PeersBroadcasted
	}
	return 0
}

func (x *BroadcastTransactionResponse) GetEncodedTransaction() string {
	if x != nil {
		return x.EncodedTransaction
	}
	return ""
}

func (x *BroadcastTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// TickInfo
type TickInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// current network tick
	Tick     uint32 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Duration uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// current epoch
	Epoch uint32 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// initial tick of epoch
	InitialTick   uint32 `protobuf:"varint,4,opt,name=initial_tick,json=initialTick,proto3" json:"initial_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickInfo) Reset() {
	*x = TickInfo{}
	mi := &file_qubic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickInfo) ProtoMessage() {}

func (x *TickInfo) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickInfo.ProtoReflect.Descriptor instead.
func (*TickInfo) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{5}
}

func (x *TickInfo) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickInfo) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TickInfo) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TickInfo) GetInitialTick() uint32 {
	if x != nil {
		return x.InitialTick
	}
	return 0
}

// GetTickInfoResponse
type GetTickInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickInfo      *TickInfo              `protobuf:"bytes,1,opt,name=tick_info,json=tickInfo,proto3" json:"tick_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickInfoResponse) Reset() {
	*x = GetTickInfoResponse{}
	mi := &file_qubic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickInfoResponse) ProtoMessage() {}

func (x *GetTickInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTickInfoResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{6}
}

func (x *GetTickInfoResponse) GetTickInfo() *TickInfo {
	if x != nil {
		return x.TickInfo
	}
	return nil
}

// GetBlockHeightResponse
type GetBlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   *TickInfo              `protobuf:"bytes,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightResponse) Reset() {
	*x = GetBlockHeightResponse{}
	mi := &file_qubic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightResponse) ProtoMessage() {}

func (x *GetBlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightResponse.ProtoReflect.Descriptor instead.
func (*GetBlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockHeightResponse) GetBlockHeight() *TickInfo {
	if x != nil {
		return x.BlockHeight
	}
	return nil
}

// AssetInfo
type AssetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	UniverseIndex uint32                 `protobuf:"varint,2,opt,name=universe_index,json=universeIndex,proto3" json:"universe_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetInfo) Reset() {
	*x = AssetInfo{}
	mi := &file_qubic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetInfo) ProtoMessage() {}

func (x *AssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetInfo.ProtoReflect.Descriptor instead.
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{8}
}

func (x *AssetInfo) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AssetInfo) GetUniverseIndex() uint32 {
	if x != nil {
		return x.UniverseIndex
	}
	return 0
}

// IssuedAssetData
type IssuedAssetData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IssuerIdentity        string                 `protobuf:"bytes,1,opt,name=issuer_identity,json=issuerIdentity,proto3" json:"issuer_identity,omitempty"`
	Type                  uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfDecimalPlaces int32                  `protobuf:"varint,4,opt,name=number_of_decimal_places,json=numberOfDecimalPlaces,proto3" json:"number_of_decimal_places,omitempty"`
	UnitOfMeasurement     []int32                `protobuf:"varint,5,rep,packed,name=unit_of_measurement,json=unitOfMeasurement,proto3" json:"unit_of_measurement,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *IssuedAssetData) Reset() {
	*x = IssuedAssetData{}
	mi := &file_qubic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuedAssetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedAssetData) ProtoMessage() {}

func (x *IssuedAssetData) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedAssetData.ProtoReflect.Descriptor instead.
func (*IssuedAssetData) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{9}
}

func (x *IssuedAssetData) GetIssuerIdentity() string {
	if x != nil {
		return x.IssuerIdentity
	}
	return ""
}

func (x *IssuedAssetData) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *IssuedAssetData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IssuedAssetData) GetNumberOfDecimalPlaces() int32 {
	if x != nil {
		return x.NumberOfDecimalPlaces
	}
	return 0
}

func (x *IssuedAssetData) GetUnitOfMeasurement() []int32 {
	if x != nil {
		return x.UnitOfMeasurement
	}
	return nil
}

// IssuedAsset
type IssuedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *IssuedAssetData       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Info          *AssetInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuedAsset) Reset() {
	*x = IssuedAsset{}
	mi := &file_qubic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedAsset) ProtoMessage() {}

func (x *IssuedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedAsset.ProtoReflect.Descriptor instead.
func (*IssuedAsset) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{10}
}

func (x *IssuedAsset) GetData() *IssuedAssetData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *IssuedAsset) GetInfo() *AssetInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// IssuedAssetsRequest
type IssuedAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuedAssetsRequest) Reset() {
	*x = IssuedAssetsRequest{}
	mi := &file_qubic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuedAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedAssetsRequest) ProtoMessage() {}

func (x *IssuedAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedAssetsRequest.ProtoReflect.Descriptor instead.
func (*IssuedAssetsRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{11}
}

func (x *IssuedAssetsRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// IssuedAssetsResponse
type IssuedAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuedAssets  []*IssuedAsset         `protobuf:"bytes,1,rep,name=issued_assets,json=issuedAssets,proto3" json:"issued_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuedAssetsResponse) Reset() {
	*x = IssuedAssetsResponse{}
	mi := &file_qubic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuedAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedAssetsResponse) ProtoMessage() {}

func (x *IssuedAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedAssetsResponse.ProtoReflect.Descriptor instead.
func (*IssuedAssetsResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{12}
}

func (x *IssuedAssetsResponse) GetIssuedAssets() []*IssuedAsset {
	if x != nil {
		return x.IssuedAssets
	}
	return nil
}

// OwnedAssetData
type OwnedAssetData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OwnerIdentity         string                 `protobuf:"bytes,1,opt,name=owner_identity,json=ownerIdentity,proto3" json:"owner_identity,omitempty"`
	Type                  uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Padding               int32                  `protobuf:"varint,3,opt,name=padding,proto3" json:"padding,omitempty"`
	ManagingContractIndex uint32                 `protobuf:"varint,4,opt,name=managing_contract_index,json=managingContractIndex,proto3" json:"managing_contract_index,omitempty"`
	IssuanceIndex         uint32                 `protobuf:"varint,5,opt,name=issuance_index,json=issuanceIndex,proto3" json:"issuance_index,omitempty"`
	NumberOfUnits         int64                  `protobuf:"varint,6,opt,name=number_of_units,json=numberOfUnits,proto3" json:"number_of_units,omitempty"`
	IssuedAsset           *IssuedAssetData       `protobuf:"bytes,7,opt,name=issued_asset,json=issuedAsset,proto3" json:"issued_asset,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OwnedAssetData) Reset() {
	*x = OwnedAssetData{}
	mi := &file_qubic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedAssetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAssetData) ProtoMessage() {}

func (x *OwnedAssetData) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAssetData.ProtoReflect.Descriptor instead.
func (*OwnedAssetData) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{13}
}

func (x *OwnedAssetData) GetOwnerIdentity() string {
	if x != nil {
		return x.OwnerIdentity
	}
	return ""
}

func (x *OwnedAssetData) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *OwnedAssetData) GetPadding() int32 {
	if x != nil {
		return x.Padding
	}
	return 0
}

func (x *OwnedAssetData) GetManagingContractIndex() uint32 {
	if x != nil {
		return x.ManagingContractIndex
	}
	return 0
}

func (x *OwnedAssetData) GetIssuanceIndex() uint32 {
	if x != nil {
		return x.IssuanceIndex
	}
	return 0
}

func (x *OwnedAssetData) GetNumberOfUnits() int64 {
	if x != nil {
		return x.NumberOfUnits
	}
	return 0
}

func (x *OwnedAssetData) GetIssuedAsset() *IssuedAssetData {
	if x != nil {
		return x.IssuedAsset
	}
	return nil
}

// OwnedAsset
type OwnedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OwnedAssetData        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Info          *AssetInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedAsset) Reset() {
	*x = OwnedAsset{}
	mi := &file_qubic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAsset) ProtoMessage() {}

func (x *OwnedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAsset.ProtoReflect.Descriptor instead.
func (*OwnedAsset) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{14}
}

func (x *OwnedAsset) GetData() *OwnedAssetData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OwnedAsset) GetInfo() *AssetInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// OwnedAssetsRequest
type OwnedAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedAssetsRequest) Reset() {
	*x = OwnedAssetsRequest{}
	mi := &file_qubic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAssetsRequest) ProtoMessage() {}

func (x *OwnedAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAssetsRequest.ProtoReflect.Descriptor instead.
func (*OwnedAssetsRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{15}
}

func (x *OwnedAssetsRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// OwnedAssetsResponse
type OwnedAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnedAssets   []*OwnedAsset          `protobuf:"bytes,1,rep,name=owned_assets,json=ownedAssets,proto3" json:"owned_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedAssetsResponse) Reset() {
	*x = OwnedAssetsResponse{}
	mi := &file_qubic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAssetsResponse) ProtoMessage() {}

func (x *OwnedAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAssetsResponse.ProtoReflect.Descriptor instead.
func (*OwnedAssetsResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{16}
}

func (x *OwnedAssetsResponse) GetOwnedAssets() []*OwnedAsset {
	if x != nil {
		return x.OwnedAssets
	}
	return nil
}

// PossessedAssetData
type PossessedAssetData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PossessorIdentity     string                 `protobuf:"bytes,1,opt,name=possessor_identity,json=possessorIdentity,proto3" json:"possessor_identity,omitempty"`
	Type                  uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Padding               int32                  `protobuf:"varint,3,opt,name=padding,proto3" json:"padding,omitempty"`
	ManagingContractIndex uint32                 `protobuf:"varint,4,opt,name=managing_contract_index,json=managingContractIndex,proto3" json:"managing_contract_index,omitempty"`
	IssuanceIndex         uint32                 `protobuf:"varint,5,opt,name=issuance_index,json=issuanceIndex,proto3" json:"issuance_index,omitempty"`
	NumberOfUnits         int64                  `protobuf:"varint,6,opt,name=number_of_units,json=numberOfUnits,proto3" json:"number_of_units,omitempty"`
	OwnedAsset            *OwnedAssetData        `protobuf:"bytes,7,opt,name=owned_asset,json=ownedAsset,proto3" json:"owned_asset,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PossessedAssetData) Reset() {
	*x = PossessedAssetData{}
	mi := &file_qubic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessedAssetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessedAssetData) ProtoMessage() {}

func (x *PossessedAssetData) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessedAssetData.ProtoReflect.Descriptor instead.
func (*PossessedAssetData) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{17}
}

func (x *PossessedAssetData) GetPossessorIdentity() string {
	if x != nil {
		return x.PossessorIdentity
	}
	return ""
}

func (x *PossessedAssetData) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PossessedAssetData) GetPadding() int32 {
	if x != nil {
		return x.Padding
	}
	return 0
}

func (x *PossessedAssetData) GetManagingContractIndex() uint32 {
	if x != nil {
		return x.ManagingContractIndex
	}
	return 0
}

func (x *PossessedAssetData) GetIssuanceIndex() uint32 {
	if x != nil {
		return x.IssuanceIndex
	}
	return 0
}

func (x *PossessedAssetData) GetNumberOfUnits() int64 {
	if x != nil {
		return x.NumberOfUnits
	}
	return 0
}

func (x *PossessedAssetData) GetOwnedAsset() *OwnedAssetData {
	if x != nil {
		return x.OwnedAsset
	}
	return nil
}

// PossessedAsset
type PossessedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *PossessedAssetData    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Info          *AssetInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PossessedAsset) Reset() {
	*x = PossessedAsset{}
	mi := &file_qubic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessedAsset) ProtoMessage() {}

func (x *PossessedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessedAsset.ProtoReflect.Descriptor instead.
func (*PossessedAsset) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{18}
}

func (x *PossessedAsset) GetData() *PossessedAssetData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PossessedAsset) GetInfo() *AssetInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// PossessedAssetsRequest
type PossessedAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PossessedAssetsRequest) Reset() {
	*x = PossessedAssetsRequest{}
	mi := &file_qubic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessedAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessedAssetsRequest) ProtoMessage() {}

func (x *PossessedAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessedAssetsRequest.ProtoReflect.Descriptor instead.
func (*PossessedAssetsRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{19}
}

func (x *PossessedAssetsRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// PossessedAssetsResponse
type PossessedAssetsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PossessedAssets []*PossessedAsset      `protobuf:"bytes,1,rep,name=possessed_assets,json=possessedAssets,proto3" json:"possessed_assets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PossessedAssetsResponse) Reset() {
	*x = PossessedAssetsResponse{}
	mi := &file_qubic_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessedAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessedAssetsResponse) ProtoMessage() {}

func (x *PossessedAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessedAssetsResponse.ProtoReflect.Descriptor instead.
func (*PossessedAssetsResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{20}
}

func (x *PossessedAssetsResponse) GetPossessedAssets() []*PossessedAsset {
	if x != nil {
		return x.PossessedAssets
	}
	return nil
}

// QuerySmartContractRequest
type QuerySmartContractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identifies the smart contract
	ContractIndex uint32 `protobuf:"varint,1,opt,name=contract_index,json=contractIndex,proto3" json:"contract_index,omitempty"`
	// identifies the function to be queried
	InputType uint32 `protobuf:"varint,2,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	// the size of the input data (request data)
	InputSize uint32 `protobuf:"varint,3,opt,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	// base64 encoded input data
	RequestData   string `protobuf:"bytes,4,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySmartContractRequest) Reset() {
	*x = QuerySmartContractRequest{}
	mi := &file_qubic_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySmartContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySmartContractRequest) ProtoMessage() {}

func (x *QuerySmartContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySmartContractRequest.ProtoReflect.Descriptor instead.
func (*QuerySmartContractRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{21}
}

func (x *QuerySmartContractRequest) GetContractIndex() uint32 {
	if x != nil {
		return x.ContractIndex
	}
	return 0
}

func (x *QuerySmartContractRequest) GetInputType() uint32 {
	if x != nil {
		return x.InputType
	}
	return 0
}

func (x *QuerySmartContractRequest) GetInputSize() uint32 {
	if x != nil {
		return x.InputSize
	}
	return 0
}

func (x *QuerySmartContractRequest) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

// QuerySmartContractResponse
type QuerySmartContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseData  string                 `protobuf:"bytes,5,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySmartContractResponse) Reset() {
	*x = QuerySmartContractResponse{}
	mi := &file_qubic_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySmartContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySmartContractResponse) ProtoMessage() {}

func (x *QuerySmartContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySmartContractResponse.ProtoReflect.Descriptor instead.
func (*QuerySmartContractResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{22}
}

func (x *QuerySmartContractResponse) GetResponseData() string {
	if x != nil {
		return x.ResponseData
	}
	return ""
}

// AssetIssuanceData
type AssetIssuanceData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IssuerIdentity        string                 `protobuf:"bytes,1,opt,name=issuer_identity,json=issuerIdentity,proto3" json:"issuer_identity,omitempty"`
	Type                  uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfDecimalPlaces int32                  `protobuf:"varint,4,opt,name=number_of_decimal_places,json=numberOfDecimalPlaces,proto3" json:"number_of_decimal_places,omitempty"`
	UnitOfMeasurement     []int32                `protobuf:"varint,5,rep,packed,name=unit_of_measurement,json=unitOfMeasurement,proto3" json:"unit_of_measurement,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AssetIssuanceData) Reset() {
	*x = AssetIssuanceData{}
	mi := &file_qubic_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetIssuanceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetIssuanceData) ProtoMessage() {}

func (x *AssetIssuanceData) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetIssuanceData.ProtoReflect.Descriptor instead.
func (*AssetIssuanceData) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{23}
}

func (x *AssetIssuanceData) GetIssuerIdentity() string {
	if x != nil {
		return x.IssuerIdentity
	}
	return ""
}

func (x *AssetIssuanceData) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AssetIssuanceData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetIssuanceData) GetNumberOfDecimalPlaces() int32 {
	if x != nil {
		return x.NumberOfDecimalPlaces
	}
	return 0
}

func (x *AssetIssuanceData) GetUnitOfMeasurement() []int32 {
	if x != nil {
		return x.UnitOfMeasurement
	}
	return nil
}

// AssetIssuance
type AssetIssuance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AssetIssuanceData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	UniverseIndex uint32                 `protobuf:"varint,3,opt,name=universe_index,json=universeIndex,proto3" json:"universe_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetIssuance) Reset() {
	*x = AssetIssuance{}
	mi := &file_qubic_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetIssuance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetIssuance) ProtoMessage() {}

func (x *AssetIssuance) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetIssuance.ProtoReflect.Descriptor instead.
func (*AssetIssuance) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{24}
}

func (x *AssetIssuance) GetData() *AssetIssuanceData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AssetIssuance) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AssetIssuance) GetUniverseIndex() uint32 {
	if x != nil {
		return x.UniverseIndex
	}
	return 0
}

// AssetIssuances
type AssetIssuances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*AssetIssuance       `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetIssuances) Reset() {
	*x = AssetIssuances{}
	mi := &file_qubic_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetIssuances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetIssuances) ProtoMessage() {}

func (x *AssetIssuances) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetIssuances.ProtoReflect.Descriptor instead.
func (*AssetIssuances) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{25}
}

func (x *AssetIssuances) GetAssets() []*AssetIssuance {
	if x != nil {
		return x.Assets
	}
	return nil
}

// AssetOwnershipData
type AssetOwnershipData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OwnerIdentity         string                 `protobuf:"bytes,1,opt,name=owner_identity,json=ownerIdentity,proto3" json:"owner_identity,omitempty"`
	Type                  uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ManagingContractIndex uint32                 `protobuf:"varint,3,opt,name=managing_contract_index,json=managingContractIndex,proto3" json:"managing_contract_index,omitempty"`
	IssuanceIndex         uint32                 `protobuf:"varint,4,opt,name=issuance_index,json=issuanceIndex,proto3" json:"issuance_index,omitempty"`
	NumberOfUnits         int64                  `protobuf:"varint,5,opt,name=number_of_units,json=numberOfUnits,proto3" json:"number_of_units,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AssetOwnershipData) Reset() {
	*x = AssetOwnershipData{}
	mi := &file_qubic_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetOwnershipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOwnershipData) ProtoMessage() {}

func (x *AssetOwnershipData) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOwnershipData.ProtoReflect.Descriptor instead.
func (*AssetOwnershipData) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{26}
}

func (x *AssetOwnershipData) GetOwnerIdentity() string {
	if x != nil {
		return x.OwnerIdentity
	}
	return ""
}

func (x *AssetOwnershipData) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AssetOwnershipData) GetManagingContractIndex() uint32 {
	if x != nil {
		return x.ManagingContractIndex
	}
	return 0
}

func (x *AssetOwnershipData) GetIssuanceIndex() uint32 {
	if x != nil {
		return x.IssuanceIndex
	}
	return 0
}

func (x *AssetOwnershipData) GetNumberOfUnits() int64 {
	if x != nil {
		return x.NumberOfUnits
	}
	return 0
}

// AssetOwnership
type AssetOwnership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AssetOwnershipData    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	UniverseIndex uint32                 `protobuf:"varint,3,opt,name=universe_index,json=universeIndex,proto3" json:"universe_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetOwnership) Reset() {
	*x = AssetOwnership{}
	mi := &file_qubic_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOwnership) ProtoMessage() {}

func (x *AssetOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOwnership.ProtoReflect.Descriptor instead.
func (*AssetOwnership) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{27}
}

func (x *AssetOwnership) GetData() *AssetOwnershipData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AssetOwnership) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AssetOwnership) GetUniverseIndex() uint32 {
	if x != nil {
		return x.UniverseIndex
	}
	return 0
}

// AssetOwnerships
type AssetOwnerships struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*AssetOwnership      `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetOwnerships) Reset() {
	*x = AssetOwnerships{}
	mi := &file_qubic_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetOwnerships) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOwnerships) ProtoMessage() {}

func (x *AssetOwnerships) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOwnerships.ProtoReflect.Descriptor instead.
func (*AssetOwnerships) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{28}
}

func (x *AssetOwnerships) GetAssets() []*AssetOwnership {
	if x != nil {
		return x.Assets
	}
	return nil
}

// AssetPossessionData
type AssetPossessionData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PossessorIdentity     string                 `protobuf:"bytes,1,opt,name=possessor_identity,json=possessorIdentity,proto3" json:"possessor_identity,omitempty"`
	Type                  uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ManagingContractIndex uint32                 `protobuf:"varint,3,opt,name=managing_contract_index,json=managingContractIndex,proto3" json:"managing_contract_index,omitempty"`
	OwnershipIndex        uint32                 `protobuf:"varint,4,opt,name=ownership_index,json=ownershipIndex,proto3" json:"ownership_index,omitempty"`
	NumberOfUnits         int64                  `protobuf:"varint,5,opt,name=number_of_units,json=numberOfUnits,proto3" json:"number_of_units,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AssetPossessionData) Reset() {
	*x = AssetPossessionData{}
	mi := &file_qubic_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetPossessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPossessionData) ProtoMessage() {}

func (x *AssetPossessionData) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPossessionData.ProtoReflect.Descriptor instead.
func (*AssetPossessionData) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{29}
}

func (x *AssetPossessionData) GetPossessorIdentity() string {
	if x != nil {
		return x.PossessorIdentity
	}
	return ""
}

func (x *AssetPossessionData) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AssetPossessionData) GetManagingContractIndex() uint32 {
	if x != nil {
		return x.ManagingContractIndex
	}
	return 0
}

func (x *AssetPossessionData) GetOwnershipIndex() uint32 {
	if x != nil {
		return x.OwnershipIndex
	}
	return 0
}

func (x *AssetPossessionData) GetNumberOfUnits() int64 {
	if x != nil {
		return x.NumberOfUnits
	}
	return 0
}

// AssetPossession
type AssetPossession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AssetPossessionData   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	UniverseIndex uint32                 `protobuf:"varint,3,opt,name=universe_index,json=universeIndex,proto3" json:"universe_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetPossession) Reset() {
	*x = AssetPossession{}
	mi := &file_qubic_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetPossession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPossession) ProtoMessage() {}

func (x *AssetPossession) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPossession.ProtoReflect.Descriptor instead.
func (*AssetPossession) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{30}
}

func (x *AssetPossession) GetData() *AssetPossessionData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AssetPossession) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AssetPossession) GetUniverseIndex() uint32 {
	if x != nil {
		return x.UniverseIndex
	}
	return 0
}

// AssetPossessions
type AssetPossessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*AssetPossession     `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetPossessions) Reset() {
	*x = AssetPossessions{}
	mi := &file_qubic_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetPossessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPossessions) ProtoMessage() {}

func (x *AssetPossessions) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPossessions.ProtoReflect.Descriptor instead.
func (*AssetPossessions) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{31}
}

func (x *AssetPossessions) GetAssets() []*AssetPossession {
	if x != nil {
		return x.Assets
	}
	return nil
}

// GetByUniverseIndexRequest
type GetByUniverseIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUniverseIndexRequest) Reset() {
	*x = GetByUniverseIndexRequest{}
	mi := &file_qubic_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUniverseIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUniverseIndexRequest) ProtoMessage() {}

func (x *GetByUniverseIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUniverseIndexRequest.ProtoReflect.Descriptor instead.
func (*GetByUniverseIndexRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{32}
}

func (x *GetByUniverseIndexRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// GetIssuedAssetsByFilterRequest
type GetIssuedAssetsByFilterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IssuerIdentity string                 `protobuf:"bytes,1,opt,name=issuer_identity,json=issuerIdentity,proto3" json:"issuer_identity,omitempty"`
	AssetName      string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIssuedAssetsByFilterRequest) Reset() {
	*x = GetIssuedAssetsByFilterRequest{}
	mi := &file_qubic_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssuedAssetsByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssuedAssetsByFilterRequest) ProtoMessage() {}

func (x *GetIssuedAssetsByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssuedAssetsByFilterRequest.ProtoReflect.Descriptor instead.
func (*GetIssuedAssetsByFilterRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{33}
}

func (x *GetIssuedAssetsByFilterRequest) GetIssuerIdentity() string {
	if x != nil {
		return x.IssuerIdentity
	}
	return ""
}

func (x *GetIssuedAssetsByFilterRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

// GetOwnedAssetsByFilterRequest
type GetOwnedAssetsByFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the issuer. Defaults to the zero address (smart contract shares).
	IssuerIdentity string `protobuf:"bytes,1,opt,name=issuer_identity,json=issuerIdentity,proto3" json:"issuer_identity,omitempty"`
	// Name of the asset (required).
	AssetName string `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	// Identity of the owner of the asset (optional).
	OwnerIdentity string `protobuf:"bytes,3,opt,name=owner_identity,json=ownerIdentity,proto3" json:"owner_identity,omitempty"`
	// Index of the contract that manages the ownership (optional).
	OwnershipManagingContract uint32 `protobuf:"varint,4,opt,name=ownership_managing_contract,json=ownershipManagingContract,proto3" json:"ownership_managing_contract,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetOwnedAssetsByFilterRequest) Reset() {
	*x = GetOwnedAssetsByFilterRequest{}
	mi := &file_qubic_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnedAssetsByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnedAssetsByFilterRequest) ProtoMessage() {}

func (x *GetOwnedAssetsByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnedAssetsByFilterRequest.ProtoReflect.Descriptor instead.
func (*GetOwnedAssetsByFilterRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{34}
}

func (x *GetOwnedAssetsByFilterRequest) GetIssuerIdentity() string {
	if x != nil {
		return x.IssuerIdentity
	}
	return ""
}

func (x *GetOwnedAssetsByFilterRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *GetOwnedAssetsByFilterRequest) GetOwnerIdentity() string {
	if x != nil {
		return x.OwnerIdentity
	}
	return ""
}

func (x *GetOwnedAssetsByFilterRequest) GetOwnershipManagingContract() uint32 {
	if x != nil {
		return x.OwnershipManagingContract
	}
	return 0
}

// GetPossessedAssetsByFilterRequest
type GetPossessedAssetsByFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the issuer (required). Defaults to the zero address (smart contract shares).
	IssuerIdentity string `protobuf:"bytes,1,opt,name=issuer_identity,json=issuerIdentity,proto3" json:"issuer_identity,omitempty"`
	// Name of the asset (required).
	AssetName string `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	// Identity of the owner of the asset (optional).
	OwnerIdentity string `protobuf:"bytes,3,opt,name=owner_identity,json=ownerIdentity,proto3" json:"owner_identity,omitempty"`
	// Identity of the possessor of the asset (optional).
	PossessorIdentity string `protobuf:"bytes,4,opt,name=possessor_identity,json=possessorIdentity,proto3" json:"possessor_identity,omitempty"`
	// Index of the contract that manages the ownership (optional).
	OwnershipManagingContract uint32 `protobuf:"varint,5,opt,name=ownership_managing_contract,json=ownershipManagingContract,proto3" json:"ownership_managing_contract,omitempty"`
	// Index of the contract that manages the possession (optional).
	PossessionManagingContract uint32 `protobuf:"varint,6,opt,name=possession_managing_contract,json=possessionManagingContract,proto3" json:"possession_managing_contract,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetPossessedAssetsByFilterRequest) Reset() {
	*x = GetPossessedAssetsByFilterRequest{}
	mi := &file_qubic_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPossessedAssetsByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPossessedAssetsByFilterRequest) ProtoMessage() {}

func (x *GetPossessedAssetsByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPossessedAssetsByFilterRequest.ProtoReflect.Descriptor instead.
func (*GetPossessedAssetsByFilterRequest) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{35}
}

func (x *GetPossessedAssetsByFilterRequest) GetIssuerIdentity() string {
	if x != nil {
		return x.IssuerIdentity
	}
	return ""
}

func (x *GetPossessedAssetsByFilterRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *GetPossessedAssetsByFilterRequest) GetOwnerIdentity() string {
	if x != nil {
		return x.OwnerIdentity
	}
	return ""
}

func (x *GetPossessedAssetsByFilterRequest) GetPossessorIdentity() string {
	if x != nil {
		return x.PossessorIdentity
	}
	return ""
}

func (x *GetPossessedAssetsByFilterRequest) GetOwnershipManagingContract() uint32 {
	if x != nil {
		return x.OwnershipManagingContract
	}
	return 0
}

func (x *GetPossessedAssetsByFilterRequest) GetPossessionManagingContract() uint32 {
	if x != nil {
		return x.PossessionManagingContract
	}
	return 0
}

// IPO
type Ipo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index of the related contract (contract address).
	ContractIndex uint32 `protobuf:"varint,1,opt,name=contract_index,json=contractIndex,proto3" json:"contract_index,omitempty"`
	// The name of the related asset.
	AssetName     string `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ipo) Reset() {
	*x = Ipo{}
	mi := &file_qubic_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipo) ProtoMessage() {}

func (x *Ipo) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipo.ProtoReflect.Descriptor instead.
func (*Ipo) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{36}
}

func (x *Ipo) GetContractIndex() uint32 {
	if x != nil {
		return x.ContractIndex
	}
	return 0
}

func (x *Ipo) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

// GetActiveIposResponse
type GetActiveIposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipos          []*Ipo                 `protobuf:"bytes,1,rep,name=ipos,proto3" json:"ipos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveIposResponse) Reset() {
	*x = GetActiveIposResponse{}
	mi := &file_qubic_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveIposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveIposResponse) ProtoMessage() {}

func (x *GetActiveIposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qubic_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveIposResponse.ProtoReflect.Descriptor instead.
func (*GetActiveIposResponse) Descriptor() ([]byte, []int) {
	return file_qubic_proto_rawDescGZIP(), []int{37}
}

func (x *GetActiveIposResponse) GetIpos() []*Ipo {
	if x != nil {
		return x.Ipos
	}
	return nil
}

var File_qubic_proto protoreflect.FileDescriptor

const file_qubic_proto_rawDesc = "" +
	"\n" +
	"\vqubic.proto\x12\x13qubic.http.qubic.pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bopenapiv3/annotations.proto\"\x86\a\n" +
	"\aBalance\x12<\n" +
	"\x02id\x18\x01 \x01(\tB,\xbaG)\x92\x02&The identity relevant to this balance.R\x02id\x12G\n" +
	"\abalance\x18\x02 \x01(\x03B-\xbaG*\x92\x02'The amount of funds the identity holds.R\abalance\x12T\n" +
	"\x0evalid_for_tick\x18\x03 \x01(\rB.\xbaG+\x92\x02(The tick that this balance is valid for.R\fvalidForTick\x12\x8c\x01\n" +
	"\x1dlatest_incoming_transfer_tick\x18\x04 \x01(\rBI\xbaGF\x92\x02CThe last tick when this identity received funds through a transfer.R\x1alatestIncomingTransferTick\x12\x88\x01\n" +
	"\x1dlatest_outgoing_transfer_tick\x18\x05 \x01(\rBE\xbaGB\x92\x02?The last tick when this identity sent funds through a transfer.R\x1alatestOutgoingTransferTick\x12Y\n" +
	"\x0fincoming_amount\x18\x06 \x01(\x03B0\xbaG-\x92\x02*The total sum of received funds over time.R\x0eincomingAmount\x12U\n" +
	"\x0foutgoing_amount\x18\a \x01(\x03B,\xbaG)\x92\x02&The total sum of sent funds over time.R\x0eoutgoingAmount\x12h\n" +
	"\x1cnumber_of_incoming_transfers\x18\b \x01(\rB'\xbaG$\x92\x02!The number of incoming transfers.R\x19numberOfIncomingTransfers\x12h\n" +
	"\x1cnumber_of_outgoing_transfers\x18\t \x01(\rB'\xbaG$\x92\x02!The number of outgoing transfers.R\x19numberOfOutgoingTransfers\"#\n" +
	"\x11GetBalanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x12GetBalanceResponse\x126\n" +
	"\abalance\x18\x01 \x01(\v2\x1c.qubic.http.qubic.pb.BalanceR\abalance\"}\n" +
	"\x1bBroadcastTransactionRequest\x12^\n" +
	"\x13encoded_transaction\x18\x01 \x01(\tB-\xbaG*\x92\x02'Base64 encoded binary transaction data.R\x12encodedTransaction\"\xdb\x02\n" +
	"\x1cBroadcastTransactionResponse\x12z\n" +
	"\x11peers_broadcasted\x18\x01 \x01(\x05BM\xbaGJ\x92\x02GThe number of Qubic node peers this transactions has been broadcast to.R\x10peersBroadcasted\x12o\n" +
	"\x13encoded_transaction\x18\x02 \x01(\tB>\xbaG;\x92\x028The Base 64 encoded binary transaction from the request.R\x12encodedTransaction\x12N\n" +
	"\x0etransaction_id\x18\x03 \x01(\tB'\xbaG$\x92\x02!The id / hash of the transaction.R\rtransactionId\"s\n" +
	"\bTickInfo\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\rR\bduration\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x12!\n" +
	"\finitial_tick\x18\x04 \x01(\rR\vinitialTick\"Q\n" +
	"\x13GetTickInfoResponse\x12:\n" +
	"\ttick_info\x18\x01 \x01(\v2\x1d.qubic.http.qubic.pb.TickInfoR\btickInfo\"Z\n" +
	"\x16GetBlockHeightResponse\x12@\n" +
	"\fblock_height\x18\x01 \x01(\v2\x1d.qubic.http.qubic.pb.TickInfoR\vblockHeight\"F\n" +
	"\tAssetInfo\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12%\n" +
	"\x0euniverse_index\x18\x02 \x01(\rR\runiverseIndex\"\xcb\x01\n" +
	"\x0fIssuedAssetData\x12'\n" +
	"\x0fissuer_identity\x18\x01 \x01(\tR\x0eissuerIdentity\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x127\n" +
	"\x18number_of_decimal_places\x18\x04 \x01(\x05R\x15numberOfDecimalPlaces\x12.\n" +
	"\x13unit_of_measurement\x18\x05 \x03(\x05R\x11unitOfMeasurement\"{\n" +
	"\vIssuedAsset\x128\n" +
	"\x04data\x18\x01 \x01(\v2$.qubic.http.qubic.pb.IssuedAssetDataR\x04data\x122\n" +
	"\x04info\x18\x02 \x01(\v2\x1e.qubic.http.qubic.pb.AssetInfoR\x04info\"1\n" +
	"\x13IssuedAssetsRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"]\n" +
	"\x14IssuedAssetsResponse\x12E\n" +
	"\rissued_assets\x18\x01 \x03(\v2 .qubic.http.qubic.pb.IssuedAssetR\fissuedAssets\"\xb5\x02\n" +
	"\x0eOwnedAssetData\x12%\n" +
	"\x0eowner_identity\x18\x01 \x01(\tR\rownerIdentity\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x18\n" +
	"\apadding\x18\x03 \x01(\x05R\apadding\x126\n" +
	"\x17managing_contract_index\x18\x04 \x01(\rR\x15managingContractIndex\x12%\n" +
	"\x0eissuance_index\x18\x05 \x01(\rR\rissuanceIndex\x12&\n" +
	"\x0fnumber_of_units\x18\x06 \x01(\x03R\rnumberOfUnits\x12G\n" +
	"\fissued_asset\x18\a \x01(\v2$.qubic.http.qubic.pb.IssuedAssetDataR\vissuedAsset\"y\n" +
	"\n" +
	"OwnedAsset\x127\n" +
	"\x04data\x18\x01 \x01(\v2#.qubic.http.qubic.pb.OwnedAssetDataR\x04data\x122\n" +
	"\x04info\x18\x02 \x01(\v2\x1e.qubic.http.qubic.pb.AssetInfoR\x04info\"0\n" +
	"\x12OwnedAssetsRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"Y\n" +
	"\x13OwnedAssetsResponse\x12B\n" +
	"\fowned_assets\x18\x01 \x03(\v2\x1f.qubic.http.qubic.pb.OwnedAssetR\vownedAssets\"\xbe\x02\n" +
	"\x12PossessedAssetData\x12-\n" +
	"\x12possessor_identity\x18\x01 \x01(\tR\x11possessorIdentity\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x18\n" +
	"\apadding\x18\x03 \x01(\x05R\apadding\x126\n" +
	"\x17managing_contract_index\x18\x04 \x01(\rR\x15managingContractIndex\x12%\n" +
	"\x0eissuance_index\x18\x05 \x01(\rR\rissuanceIndex\x12&\n" +
	"\x0fnumber_of_units\x18\x06 \x01(\x03R\rnumberOfUnits\x12D\n" +
	"\vowned_asset\x18\a \x01(\v2#.qubic.http.qubic.pb.OwnedAssetDataR\n" +
	"ownedAsset\"\x81\x01\n" +
	"\x0ePossessedAsset\x12;\n" +
	"\x04data\x18\x01 \x01(\v2'.qubic.http.qubic.pb.PossessedAssetDataR\x04data\x122\n" +
	"\x04info\x18\x02 \x01(\v2\x1e.qubic.http.qubic.pb.AssetInfoR\x04info\"4\n" +
	"\x16PossessedAssetsRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"i\n" +
	"\x17PossessedAssetsResponse\x12N\n" +
	"\x10possessed_assets\x18\x01 \x03(\v2#.qubic.http.qubic.pb.PossessedAssetR\x0fpossessedAssets\"\xa3\x01\n" +
	"\x19QuerySmartContractRequest\x12%\n" +
	"\x0econtract_index\x18\x01 \x01(\rR\rcontractIndex\x12\x1d\n" +
	"\n" +
	"input_type\x18\x02 \x01(\rR\tinputType\x12\x1d\n" +
	"\n" +
	"input_size\x18\x03 \x01(\rR\tinputSize\x12!\n" +
	"\frequest_data\x18\x04 \x01(\tR\vrequestData\"\xa4\x01\n" +
	"\x1aQuerySmartContractResponse\x12\x85\x01\n" +
	"\rresponse_data\x18\x05 \x01(\tB`\xbaG]\x92\x02ZBinary data encoded as Base64. This data is returned directly from the called SC function.R\fresponseData\"\xcd\x01\n" +
	"\x11AssetIssuanceData\x12'\n" +
	"\x0fissuer_identity\x18\x01 \x01(\tR\x0eissuerIdentity\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x127\n" +
	"\x18number_of_decimal_places\x18\x04 \x01(\x05R\x15numberOfDecimalPlaces\x12.\n" +
	"\x13unit_of_measurement\x18\x05 \x03(\x05R\x11unitOfMeasurement\"\x86\x01\n" +
	"\rAssetIssuance\x12:\n" +
	"\x04data\x18\x01 \x01(\v2&.qubic.http.qubic.pb.AssetIssuanceDataR\x04data\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12%\n" +
	"\x0euniverse_index\x18\x03 \x01(\rR\runiverseIndex\"L\n" +
	"\x0eAssetIssuances\x12:\n" +
	"\x06assets\x18\x01 \x03(\v2\".qubic.http.qubic.pb.AssetIssuanceR\x06assets\"\xd6\x01\n" +
	"\x12AssetOwnershipData\x12%\n" +
	"\x0eowner_identity\x18\x01 \x01(\tR\rownerIdentity\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x126\n" +
	"\x17managing_contract_index\x18\x03 \x01(\rR\x15managingContractIndex\x12%\n" +
	"\x0eissuance_index\x18\x04 \x01(\rR\rissuanceIndex\x12&\n" +
	"\x0fnumber_of_units\x18\x05 \x01(\x03R\rnumberOfUnits\"\x88\x01\n" +
	"\x0eAssetOwnership\x12;\n" +
	"\x04data\x18\x01 \x01(\v2'.qubic.http.qubic.pb.AssetOwnershipDataR\x04data\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12%\n" +
	"\x0euniverse_index\x18\x03 \x01(\rR\runiverseIndex\"N\n" +
	"\x0fAssetOwnerships\x12;\n" +
	"\x06assets\x18\x01 \x03(\v2#.qubic.http.qubic.pb.AssetOwnershipR\x06assets\"\xe1\x01\n" +
	"\x13AssetPossessionData\x12-\n" +
	"\x12possessor_identity\x18\x01 \x01(\tR\x11possessorIdentity\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x126\n" +
	"\x17managing_contract_index\x18\x03 \x01(\rR\x15managingContractIndex\x12'\n" +
	"\x0fownership_index\x18\x04 \x01(\rR\x0eownershipIndex\x12&\n" +
	"\x0fnumber_of_units\x18\x05 \x01(\x03R\rnumberOfUnits\"\x8a\x01\n" +
	"\x0fAssetPossession\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.qubic.http.qubic.pb.AssetPossessionDataR\x04data\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12%\n" +
	"\x0euniverse_index\x18\x03 \x01(\rR\runiverseIndex\"P\n" +
	"\x10AssetPossessions\x12<\n" +
	"\x06assets\x18\x01 \x03(\v2$.qubic.http.qubic.pb.AssetPossessionR\x06assets\"1\n" +
	"\x19GetByUniverseIndexRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\"h\n" +
	"\x1eGetIssuedAssetsByFilterRequest\x12'\n" +
	"\x0fissuer_identity\x18\x01 \x01(\tR\x0eissuerIdentity\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\"\xce\x01\n" +
	"\x1dGetOwnedAssetsByFilterRequest\x12'\n" +
	"\x0fissuer_identity\x18\x01 \x01(\tR\x0eissuerIdentity\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12%\n" +
	"\x0eowner_identity\x18\x03 \x01(\tR\rownerIdentity\x12>\n" +
	"\x1bownership_managing_contract\x18\x04 \x01(\rR\x19ownershipManagingContract\"\xc3\x02\n" +
	"!GetPossessedAssetsByFilterRequest\x12'\n" +
	"\x0fissuer_identity\x18\x01 \x01(\tR\x0eissuerIdentity\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12%\n" +
	"\x0eowner_identity\x18\x03 \x01(\tR\rownerIdentity\x12-\n" +
	"\x12possessor_identity\x18\x04 \x01(\tR\x11possessorIdentity\x12>\n" +
	"\x1bownership_managing_contract\x18\x05 \x01(\rR\x19ownershipManagingContract\x12@\n" +
	"\x1cpossession_managing_contract\x18\x06 \x01(\rR\x1apossessionManagingContract\"K\n" +
	"\x03Ipo\x12%\n" +
	"\x0econtract_index\x18\x01 \x01(\rR\rcontractIndex\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\"E\n" +
	"\x15GetActiveIposResponse\x12,\n" +
	"\x04ipos\x18\x01 \x03(\v2\x18.qubic.http.qubic.pb.IpoR\x04ipos2\x8e\x1a\n" +
	"\x10QubicLiveService\x12\xb2\x01\n" +
	"\n" +
	"GetBalance\x12&.qubic.http.qubic.pb.GetBalanceRequest\x1a'.qubic.http.qubic.pb.GetBalanceResponse\"S\xbaG:\x12\vGet Balance\x1a+Gets the balance of the specified identity.\x82\xd3\xe4\x93\x02\x10\x12\x0e/balances/{id}\x12\xd2\x01\n" +
	"\x12QuerySmartContract\x12..qubic.http.qubic.pb.QuerySmartContractRequest\x1a/.qubic.http.qubic.pb.QuerySmartContractResponse\"[\xbaG:\x12\x14Query Smart Contract\x1a\"Queries a smart contract function.\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/querySmartContract\x12\xe2\x01\n" +
	"\x14BroadcastTransaction\x120.qubic.http.qubic.pb.BroadcastTransactionRequest\x1a1.qubic.http.qubic.pb.BroadcastTransactionResponse\"e\xbaGA\x12\x15Broadcast Transaction\x1a(Broadcasts a transaction to the network.\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/broadcast-transaction\x12\x99\x01\n" +
	"\vGetTickInfo\x12\x16.google.protobuf.Empty\x1a(.qubic.http.qubic.pb.GetTickInfoResponse\"H\xbaG3\x12\rGet Tick Info\x1a\"Gets the current tick information.\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/tick-info\x12\xa8\x01\n" +
	"\x0eGetBlockHeight\x12\x16.google.protobuf.Empty\x1a+.qubic.http.qubic.pb.GetBlockHeightResponse\"Q\xbaG9\x12\x10Get Block Height\x1a#Deprecated: use /tick-info instead.P\x01\x82\xd3\xe4\x93\x02\x0f\x12\r/block-height\x12\xcf\x01\n" +
	"\x0fGetIssuedAssets\x12(.qubic.http.qubic.pb.IssuedAssetsRequest\x1a).qubic.http.qubic.pb.IssuedAssetsResponse\"g\xbaGC\x12\x12List Issued Assets\x1a-Gets assets issued by the specified identity.\x82\xd3\xe4\x93\x02\x1b\x12\x19/assets/{identity}/issued\x12\xd2\x01\n" +
	"\x0eGetOwnedAssets\x12'.qubic.http.qubic.pb.OwnedAssetsRequest\x1a(.qubic.http.qubic.pb.OwnedAssetsResponse\"m\xbaGJ\x12\x11List Owned Assets\x1a5Gets assets that are owned by the specified identity.\x82\xd3\xe4\x93\x02\x1a\x12\x18/assets/{identity}/owned\x12\xea\x01\n" +
	"\x12GetPossessedAssets\x12+.qubic.http.qubic.pb.PossessedAssetsRequest\x1a,.qubic.http.qubic.pb.PossessedAssetsResponse\"y\xbaGR\x12\x15List Possessed Assets\x1a9Gets assets that are possessed by the specified identity.\x82\xd3\xe4\x93\x02\x1e\x12\x1c/assets/{identity}/possessed\x12\xf7\x01\n" +
	"\x17GetIssuedAssetsByFilter\x123.qubic.http.qubic.pb.GetIssuedAssetsByFilterRequest\x1a#.qubic.http.qubic.pb.AssetIssuances\"\x81\x01\xbaGe\x12\x16Search Asset Issuances\x1aKReturns a list of issued assets filtered by issuer identity and asset name.\x82\xd3\xe4\x93\x02\x13\x12\x11/assets/issuances\x12\xe4\x01\n" +
	"\x1dGetIssuedAssetByUniverseIndex\x12..qubic.http.qubic.pb.GetByUniverseIndexRequest\x1a\".qubic.http.qubic.pb.AssetIssuance\"o\xbaGK\x12\x1bGet Asset Issuance By Index\x1a,Returns an asset issuance by universe index.\x82\xd3\xe4\x93\x02\x1b\x12\x19/assets/issuances/{index}\x12\x8c\x02\n" +
	"\x16GetOwnedAssetsByFilter\x122.qubic.http.qubic.pb.GetOwnedAssetsByFilterRequest\x1a$.qubic.http.qubic.pb.AssetOwnerships\"\x97\x01\xbaGz\x12\x17Search Asset Ownerships\x1a_Returns a list of asset ownerships filtered by issuer, asset name, owner and managing contract.\x82\xd3\xe4\x93\x02\x14\x12\x12/assets/ownerships\x12\xe7\x01\n" +
	"\x1cGetOwnedAssetByUniverseIndex\x12..qubic.http.qubic.pb.GetByUniverseIndexRequest\x1a#.qubic.http.qubic.pb.AssetOwnership\"r\xbaGM\x12\x1cGet Asset Ownership By Index\x1a-Returns an asset ownership by universe index.\x82\xd3\xe4\x93\x02\x1c\x12\x1a/assets/ownerships/{index}\x12\xa5\x02\n" +
	"\x1aGetPossessedAssetsByFilter\x126.qubic.http.qubic.pb.GetPossessedAssetsByFilterRequest\x1a%.qubic.http.qubic.pb.AssetPossessions\"\xa7\x01\xbaG\x88\x01\x12\x18Search Asset Possessions\x1alReturns a list of asset possessions filtered by issuer, asset name, owner, possessor and managing contracts.\x82\xd3\xe4\x93\x02\x15\x12\x13/assets/possessions\x12\xef\x01\n" +
	" GetPossessedAssetByUniverseIndex\x12..qubic.http.qubic.pb.GetByUniverseIndexRequest\x1a$.qubic.http.qubic.pb.AssetPossession\"u\xbaGO\x12\x1dGet Asset Possession By Index\x1a.Returns an asset possession by universe index.\x82\xd3\xe4\x93\x02\x1d\x12\x1b/assets/possessions/{index}\x12\xbb\x01\n" +
	"\rGetActiveIpos\x12\x16.google.protobuf.Empty\x1a*.qubic.http.qubic.pb.GetActiveIposResponse\"f\xbaGO\x12\x0fGet Active IPOs\x1a<Returns a list of IPOs that are active in the current epoch.\x82\xd3\xe4\x93\x02\x0e\x12\f/ipos/activeB\xd8\x02\xbaG\xac\x02\x12E\n" +
	"\x0eQubic HTTP API\x12,Bridge service for Qubic network operations.2\x051.0.0\x1a\x1f\n" +
	"\x1dhttps://rpc.qubic.org/live/v1:\x92\x01\n" +
	"\x10QubicLiveService\x12&Query live data from the Qubic network\x1a9\n" +
	"\x11GitHub repository\x12$https://github.com/qubic/qubic-http/\"\x1b\n" +
	"\rx-displayName\x12\n" +
	"\x12\bLive APIB-\n" +
	"\x06GitHub\x12#https://github.com/qubic/qubic-httpZ&github.com/qubic/qubic-http/protobuff/b\x06proto3"

var (
	file_qubic_proto_rawDescOnce sync.Once
	file_qubic_proto_rawDescData []byte
)

func file_qubic_proto_rawDescGZIP() []byte {
	file_qubic_proto_rawDescOnce.Do(func() {
		file_qubic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qubic_proto_rawDesc), len(file_qubic_proto_rawDesc)))
	})
	return file_qubic_proto_rawDescData
}

var file_qubic_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_qubic_proto_goTypes = []any{
	(*Balance)(nil),                           // 0: qubic.http.qubic.pb.Balance
	(*GetBalanceRequest)(nil),                 // 1: qubic.http.qubic.pb.GetBalanceRequest
	(*GetBalanceResponse)(nil),                // 2: qubic.http.qubic.pb.GetBalanceResponse
	(*BroadcastTransactionRequest)(nil),       // 3: qubic.http.qubic.pb.BroadcastTransactionRequest
	(*BroadcastTransactionResponse)(nil),      // 4: qubic.http.qubic.pb.BroadcastTransactionResponse
	(*TickInfo)(nil),                          // 5: qubic.http.qubic.pb.TickInfo
	(*GetTickInfoResponse)(nil),               // 6: qubic.http.qubic.pb.GetTickInfoResponse
	(*GetBlockHeightResponse)(nil),            // 7: qubic.http.qubic.pb.GetBlockHeightResponse
	(*AssetInfo)(nil),                         // 8: qubic.http.qubic.pb.AssetInfo
	(*IssuedAssetData)(nil),                   // 9: qubic.http.qubic.pb.IssuedAssetData
	(*IssuedAsset)(nil),                       // 10: qubic.http.qubic.pb.IssuedAsset
	(*IssuedAssetsRequest)(nil),               // 11: qubic.http.qubic.pb.IssuedAssetsRequest
	(*IssuedAssetsResponse)(nil),              // 12: qubic.http.qubic.pb.IssuedAssetsResponse
	(*OwnedAssetData)(nil),                    // 13: qubic.http.qubic.pb.OwnedAssetData
	(*OwnedAsset)(nil),                        // 14: qubic.http.qubic.pb.OwnedAsset
	(*OwnedAssetsRequest)(nil),                // 15: qubic.http.qubic.pb.OwnedAssetsRequest
	(*OwnedAssetsResponse)(nil),               // 16: qubic.http.qubic.pb.OwnedAssetsResponse
	(*PossessedAssetData)(nil),                // 17: qubic.http.qubic.pb.PossessedAssetData
	(*PossessedAsset)(nil),                    // 18: qubic.http.qubic.pb.PossessedAsset
	(*PossessedAssetsRequest)(nil),            // 19: qubic.http.qubic.pb.PossessedAssetsRequest
	(*PossessedAssetsResponse)(nil),           // 20: qubic.http.qubic.pb.PossessedAssetsResponse
	(*QuerySmartContractRequest)(nil),         // 21: qubic.http.qubic.pb.QuerySmartContractRequest
	(*QuerySmartContractResponse)(nil),        // 22: qubic.http.qubic.pb.QuerySmartContractResponse
	(*AssetIssuanceData)(nil),                 // 23: qubic.http.qubic.pb.AssetIssuanceData
	(*AssetIssuance)(nil),                     // 24: qubic.http.qubic.pb.AssetIssuance
	(*AssetIssuances)(nil),                    // 25: qubic.http.qubic.pb.AssetIssuances
	(*AssetOwnershipData)(nil),                // 26: qubic.http.qubic.pb.AssetOwnershipData
	(*AssetOwnership)(nil),                    // 27: qubic.http.qubic.pb.AssetOwnership
	(*AssetOwnerships)(nil),                   // 28: qubic.http.qubic.pb.AssetOwnerships
	(*AssetPossessionData)(nil),               // 29: qubic.http.qubic.pb.AssetPossessionData
	(*AssetPossession)(nil),                   // 30: qubic.http.qubic.pb.AssetPossession
	(*AssetPossessions)(nil),                  // 31: qubic.http.qubic.pb.AssetPossessions
	(*GetByUniverseIndexRequest)(nil),         // 32: qubic.http.qubic.pb.GetByUniverseIndexRequest
	(*GetIssuedAssetsByFilterRequest)(nil),    // 33: qubic.http.qubic.pb.GetIssuedAssetsByFilterRequest
	(*GetOwnedAssetsByFilterRequest)(nil),     // 34: qubic.http.qubic.pb.GetOwnedAssetsByFilterRequest
	(*GetPossessedAssetsByFilterRequest)(nil), // 35: qubic.http.qubic.pb.GetPossessedAssetsByFilterRequest
	(*Ipo)(nil),                               // 36: qubic.http.qubic.pb.Ipo
	(*GetActiveIposResponse)(nil),             // 37: qubic.http.qubic.pb.GetActiveIposResponse
	(*emptypb.Empty)(nil),                     // 38: google.protobuf.Empty
}
var file_qubic_proto_depIdxs = []int32{
	0,  // 0: qubic.http.qubic.pb.GetBalanceResponse.balance:type_name -> qubic.http.qubic.pb.Balance
	5,  // 1: qubic.http.qubic.pb.GetTickInfoResponse.tick_info:type_name -> qubic.http.qubic.pb.TickInfo
	5,  // 2: qubic.http.qubic.pb.GetBlockHeightResponse.block_height:type_name -> qubic.http.qubic.pb.TickInfo
	9,  // 3: qubic.http.qubic.pb.IssuedAsset.data:type_name -> qubic.http.qubic.pb.IssuedAssetData
	8,  // 4: qubic.http.qubic.pb.IssuedAsset.info:type_name -> qubic.http.qubic.pb.AssetInfo
	10, // 5: qubic.http.qubic.pb.IssuedAssetsResponse.issued_assets:type_name -> qubic.http.qubic.pb.IssuedAsset
	9,  // 6: qubic.http.qubic.pb.OwnedAssetData.issued_asset:type_name -> qubic.http.qubic.pb.IssuedAssetData
	13, // 7: qubic.http.qubic.pb.OwnedAsset.data:type_name -> qubic.http.qubic.pb.OwnedAssetData
	8,  // 8: qubic.http.qubic.pb.OwnedAsset.info:type_name -> qubic.http.qubic.pb.AssetInfo
	14, // 9: qubic.http.qubic.pb.OwnedAssetsResponse.owned_assets:type_name -> qubic.http.qubic.pb.OwnedAsset
	13, // 10: qubic.http.qubic.pb.PossessedAssetData.owned_asset:type_name -> qubic.http.qubic.pb.OwnedAssetData
	17, // 11: qubic.http.qubic.pb.PossessedAsset.data:type_name -> qubic.http.qubic.pb.PossessedAssetData
	8,  // 12: qubic.http.qubic.pb.PossessedAsset.info:type_name -> qubic.http.qubic.pb.AssetInfo
	18, // 13: qubic.http.qubic.pb.PossessedAssetsResponse.possessed_assets:type_name -> qubic.http.qubic.pb.PossessedAsset
	23, // 14: qubic.http.qubic.pb.AssetIssuance.data:type_name -> qubic.http.qubic.pb.AssetIssuanceData
	24, // 15: qubic.http.qubic.pb.AssetIssuances.assets:type_name -> qubic.http.qubic.pb.AssetIssuance
	26, // 16: qubic.http.qubic.pb.AssetOwnership.data:type_name -> qubic.http.qubic.pb.AssetOwnershipData
	27, // 17: qubic.http.qubic.pb.AssetOwnerships.assets:type_name -> qubic.http.qubic.pb.AssetOwnership
	29, // 18: qubic.http.qubic.pb.AssetPossession.data:type_name -> qubic.http.qubic.pb.AssetPossessionData
	30, // 19: qubic.http.qubic.pb.AssetPossessions.assets:type_name -> qubic.http.qubic.pb.AssetPossession
	36, // 20: qubic.http.qubic.pb.GetActiveIposResponse.ipos:type_name -> qubic.http.qubic.pb.Ipo
	1,  // 21: qubic.http.qubic.pb.QubicLiveService.GetBalance:input_type -> qubic.http.qubic.pb.GetBalanceRequest
	21, // 22: qubic.http.qubic.pb.QubicLiveService.QuerySmartContract:input_type -> qubic.http.qubic.pb.QuerySmartContractRequest
	3,  // 23: qubic.http.qubic.pb.QubicLiveService.BroadcastTransaction:input_type -> qubic.http.qubic.pb.BroadcastTransactionRequest
	38, // 24: qubic.http.qubic.pb.QubicLiveService.GetTickInfo:input_type -> google.protobuf.Empty
	38, // 25: qubic.http.qubic.pb.QubicLiveService.GetBlockHeight:input_type -> google.protobuf.Empty
	11, // 26: qubic.http.qubic.pb.QubicLiveService.GetIssuedAssets:input_type -> qubic.http.qubic.pb.IssuedAssetsRequest
	15, // 27: qubic.http.qubic.pb.QubicLiveService.GetOwnedAssets:input_type -> qubic.http.qubic.pb.OwnedAssetsRequest
	19, // 28: qubic.http.qubic.pb.QubicLiveService.GetPossessedAssets:input_type -> qubic.http.qubic.pb.PossessedAssetsRequest
	33, // 29: qubic.http.qubic.pb.QubicLiveService.GetIssuedAssetsByFilter:input_type -> qubic.http.qubic.pb.GetIssuedAssetsByFilterRequest
	32, // 30: qubic.http.qubic.pb.QubicLiveService.GetIssuedAssetByUniverseIndex:input_type -> qubic.http.qubic.pb.GetByUniverseIndexRequest
	34, // 31: qubic.http.qubic.pb.QubicLiveService.GetOwnedAssetsByFilter:input_type -> qubic.http.qubic.pb.GetOwnedAssetsByFilterRequest
	32, // 32: qubic.http.qubic.pb.QubicLiveService.GetOwnedAssetByUniverseIndex:input_type -> qubic.http.qubic.pb.GetByUniverseIndexRequest
	35, // 33: qubic.http.qubic.pb.QubicLiveService.GetPossessedAssetsByFilter:input_type -> qubic.http.qubic.pb.GetPossessedAssetsByFilterRequest
	32, // 34: qubic.http.qubic.pb.QubicLiveService.GetPossessedAssetByUniverseIndex:input_type -> qubic.http.qubic.pb.GetByUniverseIndexRequest
	38, // 35: qubic.http.qubic.pb.QubicLiveService.GetActiveIpos:input_type -> google.protobuf.Empty
	2,  // 36: qubic.http.qubic.pb.QubicLiveService.GetBalance:output_type -> qubic.http.qubic.pb.GetBalanceResponse
	22, // 37: qubic.http.qubic.pb.QubicLiveService.QuerySmartContract:output_type -> qubic.http.qubic.pb.QuerySmartContractResponse
	4,  // 38: qubic.http.qubic.pb.QubicLiveService.BroadcastTransaction:output_type -> qubic.http.qubic.pb.BroadcastTransactionResponse
	6,  // 39: qubic.http.qubic.pb.QubicLiveService.GetTickInfo:output_type -> qubic.http.qubic.pb.GetTickInfoResponse
	7,  // 40: qubic.http.qubic.pb.QubicLiveService.GetBlockHeight:output_type -> qubic.http.qubic.pb.GetBlockHeightResponse
	12, // 41: qubic.http.qubic.pb.QubicLiveService.GetIssuedAssets:output_type -> qubic.http.qubic.pb.IssuedAssetsResponse
	16, // 42: qubic.http.qubic.pb.QubicLiveService.GetOwnedAssets:output_type -> qubic.http.qubic.pb.OwnedAssetsResponse
	20, // 43: qubic.http.qubic.pb.QubicLiveService.GetPossessedAssets:output_type -> qubic.http.qubic.pb.PossessedAssetsResponse
	25, // 44: qubic.http.qubic.pb.QubicLiveService.GetIssuedAssetsByFilter:output_type -> qubic.http.qubic.pb.AssetIssuances
	24, // 45: qubic.http.qubic.pb.QubicLiveService.GetIssuedAssetByUniverseIndex:output_type -> qubic.http.qubic.pb.AssetIssuance
	28, // 46: qubic.http.qubic.pb.QubicLiveService.GetOwnedAssetsByFilter:output_type -> qubic.http.qubic.pb.AssetOwnerships
	27, // 47: qubic.http.qubic.pb.QubicLiveService.GetOwnedAssetByUniverseIndex:output_type -> qubic.http.qubic.pb.AssetOwnership
	31, // 48: qubic.http.qubic.pb.QubicLiveService.GetPossessedAssetsByFilter:output_type -> qubic.http.qubic.pb.AssetPossessions
	30, // 49: qubic.http.qubic.pb.QubicLiveService.GetPossessedAssetByUniverseIndex:output_type -> qubic.http.qubic.pb.AssetPossession
	37, // 50: qubic.http.qubic.pb.QubicLiveService.GetActiveIpos:output_type -> qubic.http.qubic.pb.GetActiveIposResponse
	36, // [36:51] is the sub-list for method output_type
	21, // [21:36] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_qubic_proto_init() }
func file_qubic_proto_init() {
	if File_qubic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qubic_proto_rawDesc), len(file_qubic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qubic_proto_goTypes,
		DependencyIndexes: file_qubic_proto_depIdxs,
		MessageInfos:      file_qubic_proto_msgTypes,
	}.Build()
	File_qubic_proto = out.File
	file_qubic_proto_goTypes = nil
	file_qubic_proto_depIdxs = nil
}
