name: Trigger Docs Update for v2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'protobuff/qubic.openapi.yaml' # Only trigger if the OpenAPI file changed

jobs:
  api-docs-update-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply OpenAPI adjustments
        run: |
          cd protobuff
          cp qubic.openapi.yaml qubic.openapi.adjusted.yaml
          yq -i '(.tags[] | select(.name == "QubicLiveService")).x-scalar-ignore = true' qubic.openapi.adjusted.yaml

      - name: Encode adjusted spec
        id: encode
        run: |
          CONTENT=$(base64 -w 0 protobuff/qubic.openapi.adjusted.yaml)
          echo "spec_base64=$CONTENT" >> "$GITHUB_OUTPUT"

      - name: Dispatch to Integration
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: qubic/integration
          event-type: live-api-update
          client-payload: '{"openapi_spec_base64": "${{ steps.encode.outputs.spec_base64 }}"}'

      - name: Dispatch to Docs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: qubic/docs
          event-type: live-api-update
          client-payload: '{"openapi_spec_base64": "${{ steps.encode.outputs.spec_base64 }}"}'
