name: Trigger Docs Update for v2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'protobuff/*.proto'

jobs:
  api-docs-update-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to qubic/integration
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: qubic/integration
          event-type: live-api-update
          client-payload: '{"ref": "${{ github.sha }}"}'

      - name: Dispatch to qubic/docs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: qubic/docs
          event-type: live-api-update
          client-payload: '{"ref": "${{ github.sha }}"}'
